apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: rhel9-persistence
spec:
  fileEvents:
    - matchPaths:
        - "/etc/cron*"
        - "/etc/systemd/system/"
        - "/etc/init.d/"
      action: "report"
